[tool.black]
line-length = 79
target-version = ['py39']
include = '\.py$'

[tool.isort]
include_trailing_comma = true
multi_line_output = 3

[tool.pydocstyle]
ignore = "D100, D2, D3, D4"
match-dir = '^(?!.*models|backbone).*$'
